### ISSUE TITLE
Data Validation Exclusão Médico

### ISSUE THREAD

**Issue by Dyastrophism** [Dyastrophism/APIRestFarmaciaMunicipal#10]
O sistema deve possuir uma funcionalidade que permita a exclusão de médicos cadastrados.

As seguintes regras de negócio devem ser validadas pelo sistema:

A exclusão não deve apagar os dados do médico, mas torná-lo como "inativo" no sistema.

**Comment by Breninho23** [comment]
Seguinte tu não precisa criar uma issue pra cada coisa faz uma pra representar o CRUD inteiro da entidade porque vai ficar tudo em uma unica classe
